### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by samlorlah** [samlorlah/first-microverse-webapp#21]
Below is a link to our project Kanban

https://github.com/samlorlah/first-microverse-webapp/projects/1.

There are 2 members in this group which are Muyiwa Fawole (Sam) and Gordon Otieno

**Comment by Nemwel-Boniface** [comment]
## Hello @samlorlah   and @GordonOtieno         :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 


There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] I have realized that you have not assigned the tasks to each other. Kindly make sure that you have assigned the tasks to each other.

**This is how I am seeing it:**

![image](https://user-images.githubusercontent.com/86318284/187186714-a4df4537-996c-46a0-8b16-8ae04d468dc5.png)

**This is how it is supposed to be:**

![image](https://user-images.githubusercontent.com/86318284/187186909-ad244f6b-2bef-4f01-933b-ed3cce82d278.png)


_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
### **Hi @samlorlah,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
### **Hi @samlorlah,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
